#ifndef DEFINICOES_SISTEMA_H_INCLUDED
#define DEFINICOES_SISTEMA_H_INCLUDED

#define true  1
#define false 0


#define NUM_ESTADOS 4
#define NUM_EVENTOS 4

// ESTADOS
enum estados {ESPERA=0, DEFINICOES, PLOTANDO, RETORNANDO};

// EVENTOS
enum eventos {NENHUM_EVENTO=-1, INICIAR, PLOTAR, RETORNAR, ENCERRAR};

// ACOES
enum acoes {NENHUMA_ACAO=-1, A01, A02, A03, A04, A05, A06};


#endif // DEFINICOES_SISTEMA_H_INCLUDED